@base_url = http://localhost:3000

###
# Adding new content into Todo list
POST {{base_url}}/new
Content-Type: application/json

{
  "content": "this is smth sus",
  "date": "{{$localDatetime iso8601}}"
}
